- hosts: hadoop
  tasks:
    - name: Copy hadoop yarn-site.xml
      copy:
        src: "{{ lookup('env','HADOOP_CONF_DIR') }}/mapred-site.xml" 
        dest: "{{ lookup('env','HADOOP_CONF_DIR') }}/mapred-site.xml"
