- hosts: hadoop
  tasks:
    - name: Copy hadoop hdfs-site.xml
      copy:
        src: "{{ lookup('env','HADOOP_CONF_DIR') }}/core-site.xml"
        dest: "{{ lookup('env','HADOOP_CONF_DIR') }}/core-site.xml"
