- hosts: hadoop
  tasks:
    - name: Copy hadoop hdfs-site.xml
      copy:
        src: "{{ lookup('env','HADOOP_CONF_DIR') }}/hadoop-env.sh"
        dest: "{{ lookup('env','HADOOP_CONF_DIR') }}/hadoop-env.sh"
