- hosts: hadoop
  tasks:
  - name: Delete Spark work directory
    file:
      path: "{{ lookup('env','SPARK_HOME') }}/work"
      state: absent

  - name: Create a directory if it does not exist
    file:
      path: "{{ lookup('env','SPARK_HOME') }}/work"
      state: directory
      mode: '0755'
