swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - text/plain
  - application/json
produces:
  - text/plain
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /statistics:
    post:
      operationId: api.notify_collector
      tags:
        - People
      summary: Create a person and add it to the people list
      description: Create a new person in the people list
      parameters:
        - name: stats
          in: body
          description: Person to create
          required: True
          schema:
            type: string
      responses:
        201:
          description: Successfully created person in list

  /newdag:
    post:
      operationId: api.notify_dag_submission
      tags:
        - DAG
      summary: Create a person and add it to the people list
      description: Create a new person in the people list
      parameters:
        - name: new_dag
          in: body
          description: Stage in execution
          required: True
          schema:
            type: string
      responses:
        201:
          description: Successfully created person in list

  /newdag2:
    post:
      operationId: api.notify_dag_submission2
      tags:
        - DAG
      summary: Create a person and add it to the people list
      description: Create a new person in the people list
      parameters:
        - name: new_dag
          in: body
          description: Stage in execution
          required: True
          schema:
            type: string
      responses:
        201:
          description: Successfully created person in list

  /newstage:
    post:
      operationId: api.notify_stage_submission
      tags:
        - Start of stage
      summary: Specify start of stage
      description: Notify cache planner with start of stage
      parameters:
        - name: new_stage
          in: body
          description: Stage in execution
          required: True
          schema:
            type: string
      responses:
        201:
          description: Successfully recieved

  /dagcompletion:
    post:
      operationId: api.notify_dag_completion
      tags:
        - People
      summary: Create a person and add it to the people list
      description: Create a new person in the people list
      parameters:
        - name: dagstr
          in: body
          description: Stage in execution
          required: True
          schema:
            type: string
      responses:
        201:
          description: Successfully recieved

  /completed:
    post:
      operationId: api.notify_experiment_completion
      tags:
        - People
      summary: Create a person and add it to the people list
      description: Create a new person in the people list
      responses:
        201:
          description: Successfully created person in list
